### ISSUE TITLE
Create fields that can choose which data to pull for export?

### ISSUE THREAD

**Issue by djamyx** [CarrieKroutil/KareoTool#1]
@CarrieKroutil This is a fantastic tool and way further along than I have been able to get trying to write my own code in Visual Studio to integrate with the Kareo API.

I'm interested in creating a gui for their API that would allow me to choose what fields to pull into an excel report from all of the available GET requests in the API.

How hard would that be to build on top of this? Would I be better off starting from scratch?!

**Comment by CarrieKroutil** [comment]
@djamyx Thank you for letting me know that you found this tool useful! 

I have taken some time to update the [README.md](https://github.com/CarrieKroutil/KareoTool/blob/master/README.md) with more information about why I built this tool and lessons learned about Kareo. 

Regarding your question, I am unsure of your use case, but I highly suggest you try Kareo's custom reports, as I outlined in the ReadMe's Preferred Solution section. E.g. https://helpme.kareo.com/01_Kareo_PM/11_Run_Reports_and_Analytics/10_Custom_Reports/Microsoft_Excel_Add-In_Instructions

If you still wanted to build a GUI for Kareo's API, then I'd suggest a bit of refactoring on this tool in the ServiceConnector project, extracting the Excel parts to another library. Then add a new project for the GUI. You can fork this repo and give your idea a try or welcome to create a branch and PR to have your changes incorporated into this repo.  

Please let me know if you have any additional thoughts or questions to discuss. 🙇‍♀️
